- package-lock.json
- package.json
- src/app/iriondaengdaeng/page.tsx
- src/types/booking.ts
- 전화번호로 api요청해서 받아오는 코드 구현
- #7
> Feat/phone num dogs view page impl/#7

- src/actions/auth.ts
- src/actions/reservation.ts
- src/app/api/reservation/route.ts
- src/types/definitions.ts
- api/reservation POST 했습니다
- #13 
-
> Feat: api/reservation POST 추가/#13

- package-lock.json
- src/actions/reservation.ts
- src/app/api/reservations/route.ts
- api/reservations get 기능 구현
- #15 
-
> feat: api/reservations get 구현/#15

- src/app/iriondaengdaeng/page.tsx
- 실행 흐름 번경 (전화번호 입력을 가장 앞단에 배치)
- 소소한 스타일 수정
- #
-
> refactor: 전화번호 입력창을 가장 앞으로 이동

- src/app/iriondaengdaeng/page.tsx
> fix: 에러 수정

- src/actions/auth.ts
> fix: 유저프로필 추가 upsert로 변경#32

- src/app/iriondaengdaeng/page.tsx
- src/constants/booking.ts
- src/types/booking.ts
> feat: 모달 팝업 사이즈 조정

- src/actions/auth.ts
- src/actions/pets.ts
- src/actions/services.ts
- src/app/api/pets/profile/route.ts
- src/app/api/reservations/route.ts
> Fix: api 수정/#36

- src/app/iriondaengdaeng/cutAgreementPage.tsx
- src/app/iriondaengdaeng/page.tsx
- tailwind.config.js
> fix: tailwind.config.js에서 생기는 오류 수정

- src/actions/reservations.ts
- src/app/api/reservations/route.ts
> Fix: api/reservations/post/#44

- src/actions/reservations.ts
- src/app/api/reservations/route.ts
> fix: reservation_id_get/#53

- src/containers/reservation/components/info_dialog.tsx
- src/containers/reservation/components/reservation_list.tsx
- src/containers/reservation/reservation_allfile.tsx
- src/services/admin/delete.tsx
- src/services/admin/put.tsx
> feat: reservation status add and delete close #56

- src/actions/reservations.ts
- src/app/api/reservations/route.ts
- 번호주면 예약 10개 받아주는 api 생성
- #58 
-
> feat: reservation phone get 추가/#58

- package.json
- src/app/iriondaengdaeng/cutAgreementPage.tsx
- react-daum-postcode 라이브러리를 추가하여, 창 띄우기 까지
- #64
- 연우님이 그 후 UI작업 해주시기로함
> feat: 임시로 주소 찾기 추가

- src/actions/auth.ts
- src/actions/pets.ts
- src/app/api/auth/profile/route.ts
- src/app/api/pets/profile/route.ts
- src/types/definitions.ts
> Fix: api/pets/profile 수정/#71

- src/app/admin/layout.tsx
- src/app/globals.css
- src/components/ui/table.tsx
- src/containers/reservation/components/option_bar.tsx
- src/containers/reservation/components/reservation_list.tsx
- src/containers/reservation/reservation_allfile.tsx
> [FEATURE] 대시보드 리스트페이지 디자인 변경 #75

- src/app/admin/layout.tsx
- src/components/side_bar/app-sidebar.tsx
- src/components/side_bar/side_bar.tsx
- src/components/ui/sidebar.tsx
- src/containers/reservation/components/reservation_list.tsx
- src/containers/reservation/reservation_allfile.tsx
- src/services/admin/get.tsx
- src/types/interface.tsx
- sidebar를 추가하고 기본적으로 닫혀있는 상태로 만듦
- sidebar에 hover시 펼쳐지도록
- #
-
> feat: add sidebar and hover action close #77

- src/actions/reservations.ts
- src/app/api/reservations/range/route.ts
- src/app/api/reservations/route.ts
- src/app/api/services/route.ts
- src/types/definitions.ts
- reservaion db를 수정한 내용 바탕으로 api 수정하기
- #101 
-
> Feat/develop/delete reservation/#101

- src/actions/pets.ts
- src/actions/reservations.ts
- src/containers/reservation/components/reservation_list.tsx
- src/containers/reservation/reservation_allfile.tsx
- src/services/admin/get.tsx
- src/types/api.ts
- src/types/definitions.ts
- 대시보드에서 리스트가 보이게 수정했습니다
- #102
- 잘못된 부분이 있을 수 있으니 보고 수정해주세요~
> Fix/develop/dashboard api fix/#102

- src/app/api/services/option/route.ts
> fix: 예약 서비스 가져오기 #104

- src/actions/additional_time_slot.ts
- src/app/api/reservations/slot/route.ts
- src/types/definitions.ts
> feat: create/get timeslot api/#97
